#!/bin/sh
# Custom AppRun for the "portable" KopiaUI AppImage.
#
# This script is installed in place of the AppRun that appimage-builder
# generates. It:
#
#   1. Sets up the bundled glibc loader + library search paths so Chromium /
#      Electron resolve every shared library from inside the AppDir instead of
#      the host (mandatory on Alpine / musl, NixOS, etc.).
#   2. Detects musl-libc hosts (Alpine) and, in that case, forces Chromium's
#      Linux user-namespace sandbox off and disables the GPU process. The
#      sandbox needs unprivileged user namespaces (often disabled on Alpine)
#      and the GPU process needs host DRI drivers that match the host kernel's
#      DRM ABI (won't match a bundled Mesa). Software rendering is acceptable
#      for a backup-tool UI.
#   3. Re-execs the bundled Electron launcher (kopia-ui.bin) under the bundled
#      ld-linux loader.
#
# All decisions made here can be overridden by the user via env vars:
#
#   KOPIA_PORTABLE_FORCE_SANDBOX=1   keep Chromium sandbox even on musl
#   KOPIA_PORTABLE_FORCE_GPU=1       keep GPU process even on musl
#   KOPIA_PORTABLE_DEBUG=1           print the resolved env + argv before exec
#
# Do not edit this file inside an installed AppImage; AppImages are read-only
# squashfs. Edit the source at app/portable-AppRun.sh in the kopia repo.

set -eu

# $APPDIR is set by the AppImage runtime; fall back to script location for
# `--appimage-extract`-and-run usage.
if [ -z "${APPDIR:-}" ]; then
    APPDIR="$(cd "$(dirname "$0")" && pwd)"
    export APPDIR
fi

# ---------------------------------------------------------------------------
# Arch detection (so the same AppRun works for x86_64 and aarch64 builds).
# ---------------------------------------------------------------------------
case "$(uname -m)" in
    x86_64|amd64)
        ARCH_TRIPLET="x86_64-linux-gnu"
        LD_LINUX="$APPDIR/lib64/ld-linux-x86-64.so.2"
        ;;
    aarch64|arm64)
        ARCH_TRIPLET="aarch64-linux-gnu"
        LD_LINUX="$APPDIR/lib/ld-linux-aarch64.so.1"
        ;;
    *)
        echo "KopiaUI portable AppImage: unsupported architecture $(uname -m)" >&2
        exit 1
        ;;
esac

# Some Ubuntu layouts put the loader under usr/lib/<triplet>/ instead.
if [ ! -x "$LD_LINUX" ]; then
    case "$ARCH_TRIPLET" in
        x86_64-linux-gnu)
            [ -x "$APPDIR/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2" ] && \
                LD_LINUX="$APPDIR/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2"
            ;;
        aarch64-linux-gnu)
            [ -x "$APPDIR/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1" ] && \
                LD_LINUX="$APPDIR/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1"
            ;;
    esac
fi

# ---------------------------------------------------------------------------
# Library + data search paths -- always point to the bundled copies first.
# ---------------------------------------------------------------------------
LD_LIBRARY_PATH="$APPDIR/usr/lib/$ARCH_TRIPLET:$APPDIR/usr/lib:$APPDIR/lib/$ARCH_TRIPLET:$APPDIR/lib"
export LD_LIBRARY_PATH

# GTK / GIO / pixbuf / fontconfig / mesa
export GTK_PATH="$APPDIR/usr/lib/$ARCH_TRIPLET/gtk-3.0"
export GIO_MODULE_DIR="$APPDIR/usr/lib/$ARCH_TRIPLET/gio/modules"
export GDK_PIXBUF_MODULEDIR="$APPDIR/usr/lib/$ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$APPDIR/usr/lib/$ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export FONTCONFIG_PATH="$APPDIR/etc/fonts"
export LIBVA_DRIVERS_PATH="$APPDIR/usr/lib/$ARCH_TRIPLET/dri"
export LIBGL_DRIVERS_PATH="$APPDIR/usr/lib/$ARCH_TRIPLET/dri"

# CA store (Alpine puts it under /etc/ssl/cert.pem, not /etc/ssl/certs/)
export SSL_CERT_FILE="$APPDIR/etc/ssl/certs/ca-certificates.crt"
export SSL_CERT_DIR="$APPDIR/etc/ssl/certs"

# ---------------------------------------------------------------------------
# musl detection. We check two signals:
#   * ldd --version output mentions "musl"
#   * /etc/alpine-release exists (Alpine specifically)
# Either is sufficient to flip the Chromium safety switches.
# ---------------------------------------------------------------------------
IS_MUSL=0
if [ -f /etc/alpine-release ]; then
    IS_MUSL=1
elif command -v ldd >/dev/null 2>&1; then
    if ldd --version 2>&1 | grep -qi musl; then
        IS_MUSL=1
    fi
fi

EXTRA_ARGS=""
if [ "$IS_MUSL" = "1" ]; then
    if [ "${KOPIA_PORTABLE_FORCE_SANDBOX:-0}" != "1" ]; then
        EXTRA_ARGS="$EXTRA_ARGS --no-sandbox"
    fi
    if [ "${KOPIA_PORTABLE_FORCE_GPU:-0}" != "1" ]; then
        EXTRA_ARGS="$EXTRA_ARGS --disable-gpu --disable-software-rasterizer"
    fi
fi

# ---------------------------------------------------------------------------
# Locate the bundled Electron launcher. The packaging hook in the
# AppImageBuilder recipe renames `kopia-ui` -> `kopia-ui.bin` so this wrapper
# can keep the canonical `AppRun` -> `kopia-ui` entry-point semantics.
# ---------------------------------------------------------------------------
TARGET="$APPDIR/kopia-ui.bin"
if [ ! -x "$TARGET" ]; then
    # Backwards-compat: fall back to un-renamed launcher.
    TARGET="$APPDIR/kopia-ui"
fi
if [ ! -x "$TARGET" ]; then
    echo "KopiaUI portable AppImage: launcher not found at $TARGET" >&2
    exit 1
fi

if [ "${KOPIA_PORTABLE_DEBUG:-0}" = "1" ]; then
    echo "APPDIR=$APPDIR" >&2
    echo "ARCH_TRIPLET=$ARCH_TRIPLET" >&2
    echo "LD_LINUX=$LD_LINUX" >&2
    echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >&2
    echo "IS_MUSL=$IS_MUSL" >&2
    echo "EXTRA_ARGS=$EXTRA_ARGS" >&2
    echo "TARGET=$TARGET" >&2
fi

# Re-exec under the bundled ld-linux when available. This is what makes the
# AppImage portable across libc implementations: the bundled glibc loader
# resolves every dependency from inside $APPDIR, never touching the host's
# libc (which may be musl).
if [ -x "$LD_LINUX" ]; then
    # shellcheck disable=SC2086
    exec "$LD_LINUX" --library-path "$LD_LIBRARY_PATH" "$TARGET" $EXTRA_ARGS "$@"
fi

# Fallback: if for some reason the bundled loader is missing, just exec
# directly. This will work on glibc hosts but is expected to fail on musl --
# in that case we'd rather fail loudly than appear to "work" only on glibc.
# shellcheck disable=SC2086
exec "$TARGET" $EXTRA_ARGS "$@"
